# Site settings
name: Matloob Altaf
title: Matloob Altaf | Full Stack Software Engineer
description: Full-stack developer building high-performance web and mobile apps
url: https://MatloobAltaf.github.io/
baseurl: ''
email: matloobAltaf.outlook.com
cover: https://MatloobAltaf.github.io/img/og.png
logo: https://MatloobAltaf.github.io/img/emojis/technologist.png
resume: https://MatloobAltaf.github.io/resume.pdf
social:
  - title: email
    url: mailto:matloob.altaf@outlook.com
  - title: twitter
    url: https://twitter.com/MatloobAltaf
  - title: instagram
    url: https://instagram.com/MatloobAltaf
  - title: codepen
    url: https://codepen.com
  - title: github
    url: https://github.com/MatloobAltaf
  - title: linkedin
    url: https://www.linkedin.com/in/MatloobAltaf

# Build settings
markdown: kramdown

exclude:
  - 'Gemfile'
  - 'Gemfile.lock'
  - '*.gemspec'
  - 'README.md'
  - 'node_modules'
  - 'build'
  - 'gulpfile.js'
  - 'package.json'

keep_files:
  - 'CNAME'
  - '.git'
  - '.gitignore'

plugins_dir:
  - jekyll-minifier
  - jekyll-sitemap
